notifications:
  email: false

language: php

php:
  - '7.4'
  - '7.3'

before_install:
  - sudo apt-get -y install dnsutils

install:
  - composer install

script:
  - make
  - mkdir -p build/logs
  - vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls -v